//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtScanner.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ArtScanner.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string PressAgain {
            get {
                return ResourceManager.GetString("PressAgain", resourceCulture);
            }
        }
        
        public static string AlignCode {
            get {
                return ResourceManager.GetString("AlignCode", resourceCulture);
            }
        }
        
        public static string NoTranslationApologise {
            get {
                return ResourceManager.GetString("NoTranslationApologise", resourceCulture);
            }
        }
        
        public static string ChooseAndGo {
            get {
                return ResourceManager.GetString("ChooseAndGo", resourceCulture);
            }
        }
        
        public static string SelectLanguagePreff {
            get {
                return ResourceManager.GetString("SelectLanguagePreff", resourceCulture);
            }
        }
        
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        public static string SaveToPref {
            get {
                return ResourceManager.GetString("SaveToPref", resourceCulture);
            }
        }
        
        public static string CannotRemove {
            get {
                return ResourceManager.GetString("CannotRemove", resourceCulture);
            }
        }
        
        public static string EmptyListRow {
            get {
                return ResourceManager.GetString("EmptyListRow", resourceCulture);
            }
        }
        
        public static string EmptyRow {
            get {
                return ResourceManager.GetString("EmptyRow", resourceCulture);
            }
        }
        
        public static string GalleryUpdated {
            get {
                return ResourceManager.GetString("GalleryUpdated", resourceCulture);
            }
        }
        
        public static string СouldNotFindQRCODE {
            get {
                return ResourceManager.GetString("СouldNotFindQRCODE", resourceCulture);
            }
        }
    }
}
